<%--*********************************************************************************************
 * Name            - Alexander Spurlock
 * Email Address   - spurloag@mail.uc.com
 * Assignment #    - Assignment #01
 * Due date        - 1/22/2020
 * Course          - IT3047C, ASP.NET
 * Semester        - Spring, 2020
 * Description     - A landing page for IT3047C, during Spring semester, year 2020
 **********************************************************************************************--%>
<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Assignment01.aspx.cs" Inherits="Assignment01" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Project Euler Problem 002</title>
    <link rel="stylesheet" type="text/css" href="StyleSheet.css"/>
</head>
<body runat="server">
    

        <header>
            <h1>
                Project Euler Problem
                2
            </h1>
        </header>
        <div class="nav-div">
        <nav>
            <ul class="ul-nav">
                <li><a href="Default.aspx">Home</a></li>
            </ul>
        </nav>
    </div>


    <div id="wrapper">
    
        
    <main>
        <form runat="server">


                <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
                <p style="text-align:center">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... </p>
                <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
        

            <p>
        

            <asp:LinkButton CssClass="submit_button" ID="btnSolve" runat="server" Text="Click To Solve" OnClick="btnSolve_Click" Font-Size="1.2em" /><asp:TextBox ID="Problem002Solution" placeholder="Solution" runat="server" Width="155px" Font-Size="1em" Height="35px" style="margin-left: 0px"></asp:TextBox></p>
        
            <asp:LinkButton target="_blank" CssClass="submit_button" ID="btnLink" runat="server" href="https://projecteuler.net/problem=2" Text="To Euler Problem" OnClick="btnLink_Click" onclientclick="btnLink_Click"/>

            <footer style="text-align:center; height: 40px; margin-top: 108px;">
            <small>
            Alexander Spurlock<br />
            spurloag@mail.uc.edu
            </small>
            </footer>
       </form>
    </main>



    </div>

    

</body>
</html>
